//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.ServicesWeb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libro
    {
        public int id_libro { get; set; }
        public string Titulo { get; set; }
        public string Sinopsis { get; set; }
        public string Autor { get; set; }
        public string Editorial { get; set; }
        public string Idioma { get; set; }
        public string Formato { get; set; }
        public string Genero { get; set; }
        public string Disponible { get; set; }
    }
}
